spring.datasource:
    username: pbluser
    password: pblpassword
    url: jdbc:mysql://81.2.255.46:3306/spots_finder1?useUnicode=yes&characterEncoding=UTF-8
spring.jpa.hibernate.ddl-auto: update
spring:
  jpa:
    show-sql: true