spring.datasource:
    username: pbluser
    password: pblpassword
    url: jdbc:mysql://localhost:3306/spots_finder1?useUnicode=yes&characterEncoding=UTF-8
spring.jpa.hibernate.ddl-auto: update
spring:
  jpa:
    show-sql: true
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      enabled: true
    encoding:
      charset: UTF-8
  messages:
    encoding: UTF-8
server:
  tomcat:
    uri-encoding: UTF-8