spring.datasource:
    username: pbluser
    password: Pblpassword1;
    url: jdbc:mysql://80.211.223.50:3306/spots_finder1?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      enabled: true
    encoding:
      charset: UTF-8
  messages:
    encoding: UTF-8
server:
  tomcat:
    uri-encoding: UTF-8