spring:
  datasource:
    data-username: pbluser
    data-password: pblpassword
    url: jdbc:mysql://localhost:3306/pbldb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true